### ISSUE TITLE
Download CelebHQ dataset

### ISSUE THREAD

**Issue by hchoi71** [EmilienDupont/neural-function-distributions#2]
Thanks for great works and also sharing very well-organized codes. 

I would like to request if you could fix the link that can download CelebHQ dataset used in your experiment. Now the provided link is not working. 

Best,

**Comment by EmilienDupont** [comment]
Thanks for flagging this! It seems like this link is no longer valid. I've added a new link where the dataset is hosted (on Kaggle): https://www.kaggle.com/datasets/lamsimon/celebahq/data.

**Comment by hchoi71** [comment]
Thanks for the link! 

I have one more question about the structure of the discriminator. As you mentioned in the code for discriminator, 'num_output_points' is roughly analogous to the number of 'pixels' in the outputs of the regular. If I just test your code with the 32x32x3 CelebA dataset, then would num_output_points=1024(32x32) be reasonable size instead of 4096(64x64)? 

From config_celebahq64.json, 

  "discriminator": {
    "norm_order": 2.0,
    "add_batchnorm": true,
    "add_weightnet_batchnorm": true,
    "deterministic": true,
    "same_coordinates": true,
    "linear_layer_sizes": [],
    "layer_configs":
    [
      {
        "out_channels": 64, 
        "num_output_points": **1024**, 
        "num_neighbors": 9, 
        "mid_channels": [16, 16, 16, 16]
      }, 
      
keep the rest same...

**Comment by EmilienDupont** [comment]
Yes that's right! This would already work, but you might also want to remove a layer from the discriminator since the input resolution is now lower (similarly to how you would remove a layer from a conv architecture when applying it to a lower resolution image).

**Comment by hchoi71** [comment]
Thanks for the explanation!
